Repository dev-floor/hongit-server, pull requests merged in 2021-08, with the labels that each got.

#66 feat(home): 홈화면 조회 api
  build.gradle.kts
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleRepositoryCustom.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleRepositoryCustomImpl.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/config/JpaConfig.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/application/HomeBoardService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/application/response/HomeResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/presentation/HomeBoardController.kt
  hongit-core/build.gradle.kts
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepository.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/board/domain/BoardRepository.kt
Labels: 🚀 enhancement

#64 feat(comment): 프로필 내 댓글 목록 조회 API
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/comment/application/CommentService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/comment/application/response/CommentInProfileResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/comment/presentation/CommentController.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/comment/domain/CommentRepository.kt
Labels: 🚀 enhancement

#65 feat(user): 프로필 내 회원 정보 조회 API
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/config/InitialDataConfig.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/UserService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/response/ProfileResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/UserController.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
Labels: 🚀 enhancement

#67 feat(user): 회원가입 API
  hongit-api/build.gradle.kts
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/config/InitialDataConfig.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/exception/ErrorMessages.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/presentation/CommonExceptionAdvice.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/security/config/AuthorizationConfig.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/security/config/SecurityConfig.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/AuthService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/application/request/JoinRequest.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
  hongit-core/build.gradle.kts
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/Email.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/UserRepository.kt
  hongit-core/src/test/kotlin/com/devfloor/hongit/core/user/domain/EmailTest.kt
Labels: 🚀 enhancement

#71 feat(documentation): REST Docs 설정 추가
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  hongit-api/build.gradle.kts
  hongit-api/src/docs/asciidoc/index.adoc
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/comment/presentation/CommentController.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/user/presentation/AuthController.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/ApiDocsTest.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/ApiDocsTestUtils.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/ApiDocumentFormatGenerator.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/user/presentation/AuthControllerDocs.kt
Labels: 📝 documentation, 🚀 enhancement, 🗻 environment

#73 feat(documentation): 게시글 상세 조회 API 문서화
  hongit-api/src/docs/asciidoc/index.adoc
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleFeedResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleHomeResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/common/utils/Constants.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleControllerDocs.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/AuthControllerDocs.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/ApiDocumentFormatGenerator.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/TestFixtures.kt
  hongit-api/src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  hongit-api/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  hongit-api/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  hongit-api/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/Article.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/common/utils/Constants.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/Email.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
Labels: 📝 documentation
