Repository dev-floor/hongit-server, pull requests merged in 2021-04, with the labels that each got.

#4 feat(environment): 개발 환경 설정
  .gitignore
  README.md
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/kotlin/com/devfloor/untitled/UntitledApplication.kt
  src/main/resources/application.yml
  src/test/kotlin/com/devfloor/untitled/UntitledApplicationTests.kt
Labels: 🗻 environment

#5 docs(template): 이슈 탬플릿 수정
  .github/ISSUE_TEMPLATE/---------template.md
Labels: 📝 documentation

#8 feature(user): 유저 엔티티 구현
  src/main/kotlin/com/devfloor/untitled/user/domain/User.kt
  src/main/kotlin/com/devfloor/untitled/user/domain/UserRepository.kt
  src/main/kotlin/com/devfloor/untitled/user/domain/UserType.kt
Labels: 🚀 enhancement

#11 refactor(user): User Entity 수정
  build.gradle.kts
  src/main/kotlin/com/devfloor/untitled/common/domain/BaseEntity.kt
  src/main/kotlin/com/devfloor/untitled/user/domain/User.kt
  src/main/kotlin/com/devfloor/untitled/user/domain/UserType.kt
Labels: 🛠 refactoring

#12 feat(article): Article 조회 구현
  build.gradle.kts
  src/main/kotlin/com/devfloor/untitled/article/application/ArticleFacade.kt
  src/main/kotlin/com/devfloor/untitled/article/application/ArticleResponse.kt
  src/main/kotlin/com/devfloor/untitled/article/application/ArticleService.kt
  src/main/kotlin/com/devfloor/untitled/article/domain/Article.kt
  src/main/kotlin/com/devfloor/untitled/article/domain/ArticleRepository.kt
  src/main/kotlin/com/devfloor/untitled/article/presentation/ArticleController.kt
  src/main/kotlin/com/devfloor/untitled/articlehashtag/application/ArticleHashtagService.kt
  src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtag.kt
  src/main/kotlin/com/devfloor/untitled/articlehashtag/domain/ArticleHashtagRepository.kt
  src/main/kotlin/com/devfloor/untitled/articleoption/application/ArticleOptionService.kt
  src/main/kotlin/com/devfloor/untitled/articleoption/domain/ArticleOption.kt
  src/main/kotlin/com/devfloor/untitled/articleoption/domain/ArticleOptionRepository.kt
  src/main/kotlin/com/devfloor/untitled/common/domain/BaseEntity.kt
  src/main/kotlin/com/devfloor/untitled/common/exception/EntityNotFoundException.kt
  src/main/kotlin/com/devfloor/untitled/common/presentation/CommonExceptionAdvice.kt
  src/main/kotlin/com/devfloor/untitled/favorite/application/ArticleFavoriteService.kt
  src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavorite.kt
  src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavoriteRepository.kt
  src/main/kotlin/com/devfloor/untitled/favorite/domain/ArticleFavoriteType.kt
  src/main/kotlin/com/devfloor/untitled/hashtag/domain/Hashtag.kt
  src/main/kotlin/com/devfloor/untitled/hashtag/domain/HashtagRepository.kt
  src/main/kotlin/com/devfloor/untitled/option/domain/Option.kt
  src/main/kotlin/com/devfloor/untitled/option/domain/OptionType.kt
  src/main/kotlin/com/devfloor/untitled/user/domain/User.kt
  src/main/kotlin/com/devfloor/untitled/user/domain/UserType.kt
Labels: 🚀 enhancement

#18 chore(environment): ktlint 플러그인, 설정 추가
  .editorconfig
  build.gradle.kts
  src/test/kotlin/com/devfloor/untitled/UntitledApplicationTests.kt
Labels: 🗻 environment
