Repository dev-floor/hongit-server, pull requests merged in 2021-10, with the labels that each got.

#78 feat(board): 게시글 목록 조회 API / 페이지네이션
  hongit-api/src/docs/asciidoc/index.adoc
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/ArticleService.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/application/response/ArticleFeedResponse.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleRepositoryCustom.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleRepositoryCustomImpl.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/domain/ArticleSortType.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/article/presentation/ArticleController.kt
  hongit-api/src/main/kotlin/com/devfloor/hongit/api/home/presentation/HomeBoardController.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleControllerDocs.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/ApiDocsTestUtils.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/TestFixtures.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/article/domain/ArticleRepository.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/articlefavorite/domain/ArticleFavorite.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/articlefavorite/domain/ArticleFavoriteRepository.kt
  hongit-core/src/main/kotlin/com/devfloor/hongit/core/user/domain/User.kt
Labels: 🚀 enhancement

#94 refactor(article): 게시글 테스트 코드 수정
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/docs/ArticleControllerDocs.kt
  hongit-api/src/test/kotlin/com/devfloor/hongit/api/support/TestFixtures.kt
Labels: 🛠 refactoring

#89 feat(environment): Log4j 로깅 추가
  .gitignore
  build.gradle.kts
  hongit-api/src/main/resources/application.yml
  hongit-api/src/main/resources/log4j2-dev.yml
  hongit-api/src/main/resources/log4j2-prod.yml
  hongit-api/src/main/resources/log4j2.yml
Labels: 🗻 environment
